sudo: required

language: perl6

os:
  - linux
  - osx

perl6:
  - 2017.12
  - latest

install:
  - echo $TRAVIS_OS_NAME
  - rakudobrew build zef
  - zef install --deps-only .

script: prove -v -e "perl6 -Ilib" t/
